name: otdartlib
version: 0.2.0
author: Dmitry Uvarov <uvarov.dl@gmail.com>
description: Operational Transform library for Dart
homepage: https://github.com/dmitryuv/otdartlib
dependencies:
  collection: any
  quiver: any
dev_dependencies:
  test: any
